import { service_category } from "@prisma/client";
export const oldTreatments = [
  {
    name: `Trattamento viso al veleno d'Api`,
    description: `È uno straordinario trattamento per il viso ricco di Veleno d’api, Revitalin e Regu-Scence ad azione rapida. In 1 ora con questo protocollo si ottiene una pulizia profonda, si avvia il rinnovo cellulare, si stimola la produzione di Collagene ed Elastina, si rigenera e tonifica l’ovale del viso, si “appiattiscono” le rughe evidenti, si riparano i danni del sole.\nDopo il trattamento l’aspetto sarà più giovane e la pelle più “tesa” e luminosa.<br>\n\nIL KIT CONTIENE UN BOX PROFESSIONALE DA UTILIZZARE IN ISTITUTO ED UN BOX DOMICILIARE DA USARE A CASA`,
    price: 72,
    img: `mfavd.webp`,
    category: service_category.viso,
  },
  {
    name: `Scrub al sale marino`,
    description: `Formidabile scrub per il corpo a doppia azione. Aiuta a ridurre gli inestetismi della cellulite, anche la più resistente, grazie all'attività detossinante e lipolitica. Grazie alle micro-particelle di Perlite esfolianti rimuove dalla cute cellule morte e impurità, rendendo così la pelle morbida, luminosa e levigata. La sua formula contiene ingredienti di origine naturale. Il massaggio, abbinato all'azione esfoliante dello scrub, favorisce la stimolazione del microcircolo e migliora l'azione detossinante.`,
    price: 60,
    img: `sasmra.webp`,
    category: service_category.corpo,
  },
  {
    name: `Pressomassaggio`,
    description: `La pressoterapia è un trattamento che migliora il rendimento del sistema circolatorio e del sistema linfatico, in chi vi si sottopone.\nTrova diversi impieghi:<br>\n• nel combattere gli inestetismi della cellulite;<br>\n•	nel ridurre la ritenzione idrica da linfedema;<br>\n• nel ridefinire alcune parti del corpo (solitamente le gambe);<br>\n• nell'incentivare l'eliminazione delle sostanze tossiche dal corpo;<br>\n• nel favorire lo snellimento di alcuni parti del corpo (in questo caso, è fondamentale anche un'adeguata attività fisica).<br>\nLa pressoterapia prevede l'applicazione di una pressione a livello della zona da trattare. Ad esercitare tale pressione sono delle specie di cuscini, che emettono getti d'aria e con i quali il terapeuta copre il paziente.\nE’ controindicata in diverse situazioni come gravidanza, diabete con microangiopatia, trombosi venosa profonda, cirrosi epatica`,
    price: 35,
    img: `pr.webp`,
    category: service_category.corpo,
  },
  {
    name: `Applicazione benggi Magic Snell Anticellulite`,
    description: `Il trattamento Magic Snell al Veleno d'Api è un trattamento riducente last minute che elimina veramente e in poco tempo i centimetri di troppo. La parte del corpo che viene trattata con lo straordinario principio attivo del veleno d’ape, viene stimolata a produrre collagene ed elastina, grazie al peptide Melitina, rinforzato da un complesso vegetale bio attivo di edera, ippocastano, centella, fucus, luppolo, rosmarino, tarassaco, betulla, rusco, alga, clorella, carota, equiseto, guaranà, trigonella, salvia, che agiscono efficacemente su cosce, glutei, pancia e braccia. Il metodo di estrazione del veleno d’api viene realizzato in Svezia e non nuoce all’ape, rispettando totalmente la sua vita.\nQuesto trattamento prevede quattro fasi in centro estetico e una fase di mantenimento domiciliare.\nRisultati visibili gia dalla prima applicazione del GIRO-VITA, GIRO-COSCE, GLUTEI E BRACCIA.`,
    price: 75,
    img: `msa.webp`,
    category: service_category.corpo,
  },
  {
    name: `Fango ad azione tonificante`,
    description: `Fango cosmetico a base di Argilla Verde Micronizzata e Caolino. Contiene Olio di Jojoba Ozonizzato che unisce alla proprietà idratante, un'attività stimolante sulla circolazione, apportando benefici anche al tono e all'elasticità della pelle. Al suo interno si trovano gli Estratti di Fucus (Quercia Marina), Edera, Centella e Betulla noti per il loro proprietà drenanti e tonificanti e gli Oli Essenziali, di Menta ed Eucalipto ad azione rinfrescante.`,
    price: 60,
    img: `faat.webp`,
    category: service_category.corpo,
  },
  {
    name: `Eosonic silhouette sculptor`,
    description: `Eosonic è un sistema rivoluzionario, ideato per agire rapidamente ed efficacemente sul dimagrimento localizzato\ne sugli inestetismi della cellulite. Eosonic è l'unica apparecchiatura al mondo a sfruttare contemporaneamente la sinergia di 4 importanti tecnologie: ultrasuoni, elettrostimolazione, raggi infrarossi e cromoterapia.`,
    price: 90,
    img: `ess.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Articolare`,
    description: `<b>Massaggio Articolare</b>:<br>\nRiattiva e migliora le funzioni della circolazione sanguigna, delle articolazioni, dei tessuti e dei muscoli.<br>\n<b>Massaggio Hot Stone</b>:<br>\nL’Hot Stone massage è un massaggio Olistico che tratta mente e corpo. L’applicazione delle mani, in congiunzione con le pietre, produce un’intensificazione del contatto. L’energia prodotta dal massaggio con le pietre promuove un effetto armonizzante e purificante tale da indurre uno stato meditativo in quiete e calma. Dal punto di vista spirituale questo massaggio dona inoltre una generale sensazione di benessere, relax fisico e mentale con conseguente miglioramento dell’umore.`,
    price: 60,
    img: `maohs.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Connettivale`,
    description: `E’ una tecnica di massaggio che agisce sugli strati profondi dei tessuti sottostanti, eliminando\nle tossine che vi si depositano a seguito di eventi stressanti.\nIl massaggio connettivale trae efficacia da stimoli cutanei e sotto-cutanei di zone riflessogene e dipende dai rapporti dell'innervazione che provengono dallo stesso livello metamerico tra tessuti cutanei ed organi viscerali.\nVuol dire che a via riflessa, massaggiando il corpo dal fuori si ottiene il beneficio dentro nel corpo - grazie la sistema nervosa e i legamenti fasciali.\nAllora, grazie alle particolari manovre, tale massaggio stimola la circolazione a livello locale, e il maggior apporto d' ossigeno alla parte trattata.`,
    price: 54,
    img: `mc.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Decontratturante`,
    description: `Il massaggio decontratturante è un tipo di massaggio che agisce in profondità sui tessuti connettivi e muscolari, con il preciso scopo di sciogliere contratture e, più in generale, tensioni della muscolatura`,
    price: 60,
    img: `md.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Drenante`,
    description: `Il Massaggio drenante è una sequenza di movimenti lenti e ritmati che ha come caratteristica inderogabile " l'apertura" delle stazioni linfatiche principali. L'apertura consiste in una combinazione di movimenti leggeri circolari: rotondi o ovali. Successivamente viene trattata la zona indicata del corpo con il principio di manovre con "Spinta massima e pressione zero" per favorire il drenaggio della linfa e alla fine si riesegue la "chiusura" delle stazioni linfatiche precedentemente aperte. Il metodo non può essere applicato su tutto il corpo nella medesima seduta. I benefici e gli effetti del massaggio drenante sono infatti molteplici. Il massaggio drenante riduce la ritenzione idrica e gli inestetismi della pelle, favorendo la circolazione linfatica e drenando i liquidi in eccesso. Inoltre depura l'organismo e distende le fibre muscolari con effetto rilassante sull'intero sistema nervoso.`,
    price: 60,
    img: `mdr.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Estetico`,
    description: `Il massaggio agisce su tutto il nostro corpo, influenzando: il sistema\nnervoso, la circolazione del sangue, la muscolatura, il sistema\nscheletrico, il sistema ormonale, il sistema respiratorio ed il sistema\ndigestivo. A seconda delle manovre, delle tecniche e dei prodotti\nutilizzati si può scegliere tra massaggi tonificanti, rilassanti o\nantistress.`,
    price: 45,
    img: `me.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Miofasciale`,
    description: `Il massaggio miofasciale è una tecnica di massaggio che lavora in profondità agendo sulla fascia del muscolo e sul tessuto connettivale resistente, che riveste i ventri muscolari, li unisce l'un l'altro e ne permette il reciproco scorrimento. \nIl miofasciale si pratica con le mani, gli avambracci e i gomiti, tra le manualità utilizzate troviamo l'allungamento dolce ma profondo.\nTale massaggio è in grado di riequilibrare gli squilibri fasciali, migliorare la postura, eliminando le tossine e risolvendo i dolori muscolo-articolari.\nI vantaggi del massaggio miofasciale sono quelli di aumentare l'apporto ematico, di migliorare il deflusso venoso e linfatico.`,
    price: 54,
    img: `mm.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Rilassante`,
    description: `Il massaggio rilassante è caratterizzato dall’essere eseguito con movimenti lenti e avvolgenti che esercitano pressioni più o meno profonde, ma comunque sempre ritmiche e fluide su varie zone del corpo. Il massaggio rilassante serve a tutte quelle persone che sono vittime dello stress e dell’ansia, fenomeni molto diffusi che si ripercuotono negativamente non solo sulla mente ma anche sul corpo. Una persona stressata e ansiosa tende a irrigidire varie parti del corpo (il collo, la schiena, l’addome, ecc.) causando dolori e contratture sia muscolari, sia articolari, sia a livello degli organi interni.`,
    price: 54,
    img: `mr.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Snellente`,
    description: `La tecnica del massaggio snellente prevede movimenti di pressione, frizione ed impastatura che vengono praticati sui cuscinetti adiposi. Le manovre del massaggiatore saranno molto energiche, perché questa tecnica agisce sul tessuto adiposo più compatto. In linea generale, aiuta il metabolismo a funzionare in modo corretto ed evita quei gonfiori che si accumulano nelle gambe, sui glutei o all'altezza dell'addome. In pratica le mani del massaggiatore spostano il liquido che di solito si trova nella pelle o tra pelle e muscoli e lo fa uscire dai vasi linfatici. Tramite questo massaggio i cuscinetti adiposi di gambe, cosce, glutei, fianchi ed addome appaiono ammorbiditi fin dalle prime sedute così come migliora in maniera evidente il gonfiore alle gambe e alle caviglie.`,
    price: 60,
    img: `msk.webp`,
    category: service_category.corpo,
  },
  {
    name: `Pulizia viso “Bellezza” -30 minuti`,
    description: `• Detersione: detersione accurata della pelle utilizzando un detergente adatto alla tipologia cutanea; tonificazione utilizzando una lozione tonica analcolica adatta alla tipologia cutanea;<br>\n• Scrub: per favorire il distacco delle lamelle cornee superficiali che mescolandosi al sebo e alle impurità formano un tappo che blocca l'ostio follicolare causando la formazione del comedone;<br>\n• Maschera: applicazione della maschera personalizzata adatta al tipo di pelle;<br> \n• Massaggio viso con crema specifica.`,
    price: 30,
    img: `pvb.webp`,
    category: service_category.viso,
  },
  {
    name: `Pulizia Viso Profonda- 1 ORA`,
    description: `• Detersione: detersione accurata della pelle utilizzando un detergente adatto alla tipologia cutanea;Tonificazione utilizzando una lozione tonica analcolica adatta alla tipologia cutanea;<br>\n• Scrub: per favorire il distacco delle lamelle cornee superficiali che mescolandosi al sebo e alle impurità formano un tappo che blocca l'ostio follicolare causando la formazione del comedone;<br>\n• Vaporizzatore: vapore caldo ozonizzato per ottimizzare la preparazione della pelle e facilitare l'estrazione manuale delle impurità e dei comedoni;<br>\n• Eliminazione manuale accurata e delicata dei comedoni;<br>\n• Applicazione di un siero concentrato adatto al tipo di pelle ad effetto: calmante/disarrossante, sebo-equilibrante, idratante/nutriente, tonificante/restitutivo;<br>\n• Maschera: applicazione della maschera personalizzata adatta al tipo di pelle; <br>\n• Eliminazione dei residui di maschera e tonificazione;<br>\n• Conclusione del trattamento con l'applicazione di un cosmetico idratante/protettivo secondo la tipologia cutanea.<br>`,
    price: 50,
    img: `pvsc.webp`,
    category: service_category.viso,
  },
  {
    name: `Trattamento Viso specifico “Beautiful”`,
    description: `Pulizia di viso profonda + ultrasuono, favorevole la maggior penetrazione della fiala magica.`,
    price: 60,
    img: `tvsb.webp`,
    category: service_category.viso,
  },
  {
    name: `Trattamento Viso specifico "Lifting"`,
    description: `• Detersione: detersione accurata della pelle utilizzando un detergente adatto alla tipologia cutanea;Tonificazione utilizzando una lozione tonica analcolica adatta alla tipologia cutanea; <br>\n• Scrub: beautiful permette di realizzare uno scrub con applicatore a lama, per un peeling profondo. L’aumento dell’apporto nutritivo dei capillari interessati dal trattamento (Iperemia) stimola la circolazione localizzata, contribuendo al turn over cellulare e migliorando notevolmente l’idratazione dermica, per una pelle visibilmente più luminosa e setosa; <br>\n• Lifting elettrostimolazione microstimolazione: l’azione elettrostimolante differenziata, agisce sulla muscolatura del viso laddove è necessario tonificare e recuperare la forma muscolare unitamente al miglioramento dell’aspetto dell’epidermide. Quest’effetto è coadiuvato dal drenaggio elettro-linfatico che, associato alla contrazione involontaria delle fasce muscolari, permette di ottenere un visibile miglioramento dell’aspetto della pelle, "effetto Lifting", coadiuvato da un maggior tono muscolare; <br>\n• Maschera: per il tipo di pelle che si sta trattando con aggiunta di crema.`,
    price: 70,
    img: `tvsl.webp`,
    category: service_category.viso,
  },
  {
    name: `Trattamento Viso per tutti i tipi di pelle`,
    description: `Le Bacche di Goji sono i frutti di una pianta originaria degli altopiani asiatici di Cina, Tibet e Mongolia. Questi piccoli frutti rossi sono apprezzati nel mondo per le loro riconosciute qualità terapeutiche e nutritive, e da sempre sono un elemento chiave della medicina tradizionale cinese. Ricche di vitamine, sali minerali e aminoacidi, le bacche di Goji rappresentano un notevole antiossidante naturale.<br>\nLa bacca di Goji Contiene Vitamina C in concentrazione tripla rispetto a quella dell’arancia, vanta il più alto contenuto di Vitamina B tra i frutti in natura e contiene più Betacarotene delle stesse carote.\nla Vitamina C agisce contro i radicali liberi e contrasta l’invecchiamento cutaneo, rendendo le Bacche di Goji un potente antiage naturale.<br>\nLe Vitamine del gruppo B proteggono la pelle dall'azione dei raggi solari e partecipano alla trasformazione dei lipidi e dei glucidi, inoltre contribuiscono a regolare la produzione di sebo aiutando a mantenere il giusto grado di idratazione della pelle. \nil Betacarotene ha effetti positivi sul processo di rinnovamento della pelle ed anch’esso protegge dai danni derivanti dai radicali liberi e dal sole.<br>\nQuesta azione sinergica rende la pelle compatta, morbida ed elastica ed attenua sensibilmente i segni dell’invecchiamento cutaneo.<br>\n<br>\nPrincipi attivi:<br>\n<br>\n<b>PREVENTHELIA</b>: Un tetrapeptide che combatte gli effetti nocivi dalle radiazioni UV sulla pelle, proteggendo il dna e stimolando il sistema di riparazione, limitando i segni prematuri del fotoinvecchiamento ed aumentando al contempo la vitalità cellulare.\n<br><br>\n<b>SYN-TC</b>: il syn-tC è una molecola complessa composta da tripeptidi e tetrapeptidi, la cui combinazione offre la possibilità di interazione con la struttura delle più rilevanti proteine della pelle, incrementando e stimolando la produzione di collagene, riducendo in modo visibile le rughe del viso e le fastidiose “zampe di gallina”. Questo versatile principio attivo contribuisce anche a prevenire i danni da fotoinvecchiamento ed a rendere la pelle più compatta e morbida.<br><br>\n\n<b>VITAMINA</b>: è la vitamina e possiede un’elevata attività antiossidante, neutralizza la reattività dei radicali liberi, bloccando lo stress ossidativo responsabile dei danni alle cellule. migliora l’idratazione cutanea e la capacità di trattenere acqua negli strati cutanei.<br><br>\n\n<b>ACIDO JALURONICO</b>: trattenendo efficacemente le molecole d’acqua, contribuisce a regalare morbidezza ed elasticità alla pelle, nutrendola in profondità e contrastando le rughe d’espressione.`,
    price: 72,
    img: `tvptitdp.webp`,
    category: service_category.viso,
  },
  {
    name: `Trattamento Viso per pelli sensibili`,
    description: `I mirtilli rossi hanno proprietà rinfrescanti, astringenti, toniche, e diuretiche e contengono numerosi principi attivi, fra cui le vitamine A e C, l’acido citrico e quello malico, la mirtillina e minerali quali fosforo, calcio e manganese. L’azione di questi principi rinforza le pareti dei capillari, aiutando cosi le pelli più sensibili e predisposte alle irritazioni.<br>\nIn Italia i mirtilli sono distribuiti nei boschi o sottoboschi delle Alpi e dell’Appennino, dove possiamo trovarli fino ad un’altitudine di 1500-1800 metri. Si conoscono più di 130 specie, ma il mirtillo nero e rosso sono le due maggiormente studiate e utilizzate per le loro spiccate proprietà terapeutiche e cosmetiche. <br>\nIl loro colore si deve alla presenza di Antociani, pigmenti dalle spiccate proprietà antiossidanti, che vengono, da alcuni, paragonati ad un vero e proprio antidoto naturale contro l’invecchiamento.<br>\nLe bacche dei mirtilli sono ricche di tannini e di flavonoidi che hanno un’azione Antiossidante e anti radicali liberi.<br><br>\n\nPrincipi attivi:<br><br>\n\n<b>PREVENTHELIA</b>: un tetrapeptide che combatte gli effetti nocivi dalle radiazioni UV sulla pelle, proteggendo il dna e stimolando il sistema di riparazione, limitando i segni prematuri del fotoinvecchiamento ed aumentando al contempo la vitalità cellulare.<br><br>\n\n<b>SYN-TC</b>: il syn-tC è una molecola complessa composta da tripeptidi e tetrapeptidi, la cui combinazione offre la possibilità di interazione con la struttura delle più rilevanti proteine della pelle, incrementando e stimolando la produzione di collagene, riducendo in modo visibile le rughe del viso e le fastidiose “zampe di gallina”. Questo versatile principio attivo contribuisce anche a prevenire i danni da fotoinvecchiamento ed a rendere la pelle più compatta e morbida.<br><br>\n\n<b>VITAMINA</b>: è la vitamina e possiede un’elevata attività antiossidante, neutralizza la reattività dei radicali liberi, bloccando lo stress ossidativo responsabile dei danni alle cellule. migliora l’idratazione cutanea e la capacità di trattenere acqua negli strati cutanei.<br><br>\n\n<b>ACIDO JALURONICO</b>: trattenendo efficacemente le molecole d’acqua, contribuisce a regalare morbidezza ed elasticità alla pelle, nutrendola in profondità e contrastando le rughe d’espressione.`,
    price: 72,
    img: `tvpps.webp`,
    category: service_category.viso,
  },
  {
    name: `Trattamento Viso per pelli mature over 40`,
    description: `Il melograno (Punica Granatum) è una pianta originaria dell’Asia sud-occidentale, diffuso oggi anche in Italia soprattutto a scopo decorativo. Particolarmente ricercato, è ricco di acido alfa-punicico (omega-5), contiene inoltre le Vitamine E ed F, oltre a diversi acidi grassi quali l’acido oleico, linoleico, palmitico e stearico. \nConsigliato per le pelli stressate, mature e sensibili. Ha un’azione lenitiva sulla pelle irritata e risulta perciò molto efficace come riparatore. Restringe i pori della pelle conferendole un effetto mat. Tutti questi elementi contribuiscono a nutrire la pelle, ripristinando in particolare i livelli di Acido Jaluronico e contrastando i radicali liberi. \nUtilizzare cosmetici a base di melograno, pertanto, significa far godere la propria pelle di tutti i componenti bioattivi presenti al suo interno per supportare la lotta del viso contro l’età e contro:<br>\n• rughe e perdita di tono;<br>\n• macchie;<br>\n• disidratazione e pelle secca. <br>\nPer questo motivo i cosmetici a base di Melograno sono consigliati soprattutto dopo i 40 anni, quando i cambiamenti dovuti all’età e al fotoinvecchiamento divengono spiacevolmente visibili. La loro azione antiage è stata comprovata nel corso di numerosi test.<br><br>\n\nPrincipi attivi:<br><br>\n\n<b>PREVENTHELIA</b>: un tetrapeptide che combatte gli effetti nocivi dalle radiazioni UV sulla pelle, proteggendo il dna e stimolando il sistema di riparazione, limitando i segni prematuri del fotoinvecchiamento ed aumentando al contempo la vitalità cellulare.<br><br>\n\n<b>SYN-TC</b>: il syn-tC è una molecola complessa composta da tripeptidi e tetrapeptidi, la cui combinazione offre la possibilità di interazione con la struttura delle più rilevanti proteine della pelle, incrementando e stimolando la produzione di collagene, riducendo in modo visibile le rughe del viso e le fastidiose “zampe di gallina”. Questo versatile principio attivo contribuisce anche a prevenire i danni da fotoinvecchiamento ed a rendere la pelle più compatta e morbida.<br><br>\n\n<b>VITAMINA</b>: è la vitamina e possiede un’elevata attività antiossidante, neutralizza la reattività dei radicali liberi, bloccando lo stress ossidativo responsabile dei danni alle cellule. migliora l’idratazione cutanea e la capacità di trattenere acqua negli strati cutanei.<br><br>\n\n<b>ACIDO JALURONICO</b>: trattenendo efficacemente le molecole d’acqua, contribuisce a regalare morbidezza ed elasticità alla pelle, nutrendola in profondità e contrastando le rughe d’espressione.`,
    price: 72,
    img: `tvppmo4.webp`,
    category: service_category.viso,
  },
  {
    name: `Trucco Giorno`,
    description: `È un trucco leggero chi è adatto per il vostro quotidiano.`,
    price: 25,
    img: `tg.webp`,
    category: service_category.make_up,
  },
  {
    name: `Trucco per la Sera`,
    description: `È un trucco adatto per le feste. È un po più pesante rispetto al "Trucco da Giorno".`,
    price: 32,
    img: `tps.webp`,
    category: service_category.make_up,
  },
  {
    name: `Trucco Sposa`,
    description: `È il trucco per il Vostro matrimonio da sogno.`,
    price: 90,
    img: `ts.webp`,
    category: service_category.make_up,
  },
  {
    name: `Prova Trucco Sposa`,
    description: `Questa prova si effettua prima del vero e proprio giorno del matrimonio. Ha il compito di provare varie tecniche e colori per decidere insieme a Voi la giusta misura del Trucco Sposa.`,
    price: 25,
    img: `pts.webp`,
    category: service_category.make_up,
  },
  {
    name: `Ceretta Completa Donna`,
    description: `L'epilazione completa del corpo riguarda tutto il corpo, ovvero le gambe, le braccia, il viso, la zona intima, le acelle, la pancia e il seno.`,
    price: 55,
    img: `etc.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Braccia`,
    description: `Il trattamento consiste nella ceretta di tutte e due le braccia.`,
    price: 15,
    img: `eb.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Gambe`,
    description: `È la ceretta delle entrambe gambe.`,
    price: 25,
    img: `eg.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta mezza Gamba`,
    description: `È la ceretta delle mazza gambe. Potete scegliere tra coscia o gamba-il prezzo è uguale.`,
    price: 20,
    img: `emg.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Intima`,
    description: `È la ceretta dell' inguine parziale- zona bikini. Il periodo consigliato d' effettuarlo è dopo il ciclo mestruale per sentire meno dolore.`,
    price: 10,
    img: `ei.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Intima Completa`,
    description: `È la ceretta dell'inguine integrale con incluso il sedere. Il periodo consigliato di effettuare questo trattamento è dopo il ciclo mestruale, per sentire meno dolore.`,
    price: 13,
    img: `eit.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Ascelle`,
    description: `La ceretta delle ascelle aiuta di combattere contro il problema della sudorazione eccessiva sia nelle donne che negli uomini e crea un confort estetico sopratutto al estate.`,
    price: 10,
    img: `ea.jpeg`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Sopracciglia`,
    description: `La depilazione delle sopracciglia di una persona è necessaria per valorizzare e sottolineare lo sguardo. Si usano varie tecniche per rimuovere i peli superflui: a ceretta, a pinzetta e pure le forbici.`,
    price: 10,
    img: `ds.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Ceretta Baffetti`,
    description: `È la ceretta dei baffi della donna.`,
    price: 6,
    img: `edb.webp`,
    category: service_category.ceretta,
  },
  {
    name: `Rimozione semipermanente+Manicure estetico`,
    description: `Taglio unghie e pellicine; limatura; togliere smalto e massaggio mani con crema.`,
    price: 25,
    img: `m.webp`,
    category: service_category.manicure,
  },
  {
    name: `Manicure Semipermanente`,
    description: `È la manicure completa+ smalto semipermanente.`,
    price: 35,
    img: `ms.webp`,
    category: service_category.manicure,
  },
  {
    name: `Pedicure`,
    description: `Il trattamento include: Mettere i Piedi al ammollo con scrub esfoliante; taglio unghie e pellicine; raspare le duroni e i talloni; limatura; mettere lo smalto. Massaggio ai piedi con la crema.`,
    price: 28,
    img: `p.webp`,
    category: service_category.pedicure,
  },
  {
    name: `Pedicure+ Semipermanente`,
    description: `Il trattamento consiste in esecuzione di pedicure estetico a secco+ applicazione di smalto semipermanente che va asciugato sotto la lampada U.V. Il metodo permette di avere una lucidezza assoluta delle unghie dei piedi per un mese intero, come se fossi appena fatto lo smalto.`,
    price: 35,
    img: `ps.webp`,
    category: service_category.pedicure,
  },
  {
    name: `Massaggio piedi`,
    description: `È un massaggio per 30 minuti ai piedi con olio caldo. Il trattamento ottiene pieno relax e sgonfiamento delle piedi affaticati.`,
    price: 25,
    img: `mp.webp`,
    category: service_category.pedicure,
  },
  {
    name: `Pedicure Avanzato`,
    description: `Il trattamento di pedicure mette in assoluto ordine i piedi trascurati. Si effettua pediluvio+ scrub esfoliante; taglio unghie problematiche; togliere i eventuali duroni e limare con fresa eventuali unghie ispessite. Massaggio finale con la crema piedi.`,
    price: 32,
    img: `pa.webp`,
    category: service_category.pedicure,
  },
  {
    name: `Manicure Estetico`,
    description: `Procedimento del trattamento: <br>\n• si mettono le mani in acqua;<br>\n• le unghie vengono tagliate<br>\n• le pellicine vengono spinte e tagliate;<br>\n• limatura;<br>\n• si mette lo smalto;<br>\n• asciugatura e massaggio della mano con crema.<br>`,
    price: 18,
    img: `mest.webp`,
    category: service_category.manicure,
  },
  {
    name: `Manicure in Gel`,
    description: `Si effettua un trattamento manicure estetico dopodiché si applica il gel sull'unghia naturale.`,
    price: 45,
    img: `mig.webp`,
    category: service_category.manicure,
  },
  {
    name: `Ricostruzione(ALLUNGAMENTO) Unghie in Gel`,
    description: `Si effettua un trattamento manicure estetico dopodiché le unghie vengono allungate tramite la ricostruzione.`,
    price: 60,
    img: `ruig.webp`,
    category: service_category.manicure,
  },
  {
    name: `Doccia solare bassa pressione 8min`,
    description: `Doccia solare a bassa pressione adatta al mantenimento dell'abbronzatura, per chi è già abbronzato o vuole diventarlo. Seduta singola da 8 minuti nella doccia solare <b>TECNOSOLE</b>.`,
    price: 7,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Doccia solare bassa pressione 10min`,
    description: `Doccia solare a bassa pressione adatta al mantenimento dell'abbronzatura, per chi è già abbronzato o vuole diventarlo. Seduta singola da 10 minuti nella doccia solare <b>TECNOSOLE</b>.`,
    price: 8,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Doccia solare bassa pressione 12min`,
    description: `Doccia solare a bassa pressione adatta al mantenimento dell'abbronzatura, per chi è già abbronzato o vuole diventarlo. Seduta singola da 12 minuti nella doccia solare <b>TECNOSOLE</b>.`,
    price: 9,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Doccia solare bassa pressione 15min`,
    description: `Doccia solare a bassa pressione adatta al mantenimento dell'abbronzatura, per chi è già abbronzato o vuole diventarlo. Seduta singola da 15 minuti nella doccia solare <b>TECNOSOLE</b>.`,
    price: 12,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Seduta singola`,
    description: `Una seduta singola di 40 minuti presso la grotta di sale himalayano.`,
    price: 20,
    img: `ss.webp`,
    category: service_category.grotta_di_sale,
  },
  {
    name: `Seduta singola special`,
    description: `Una seduta singola di 40 minuti presso la grotta di sale himalayano. Vale solo per i ragazzi dai 10 ai 17 anni e gli anziani sopra i 60 anni.`,
    price: 15,
    img: `sss.webp`,
    category: service_category.grotta_di_sale,
  },
  {
    name: `Abbonamento Grotta di Sale #1`,
    description: `5 sedute (+1 in omaggio) da 40 minuti ciascuna nella grotta di sale himalayano a soli 90 euro.`,
    price: 100,
    img: `ssss.webp`,
    category: service_category.grotta_di_sale,
  },
  {
    name: `Abbonamento Grotta di Sale #2`,
    description: `10 sedute (+2 in omaggio) da 40 minuti ciascuna nella grotta di sale himalayano a soli 180 euro.`,
    price: 180,
    img: `ssss4.webp`,
    category: service_category.grotta_di_sale,
  },
  {
    name: `Abbonamento Solarium (8min) #1`,
    description: `5 sedute da 8 minuti + 1 in omaggio`,
    price: 35,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (8min) #2`,
    description: `9 sedute da 8 minuti + 1 in omaggio`,
    price: 63,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (10 Min.) #1`,
    description: `5 sedute da 10 minuti + 1 in omaggio`,
    price: 40,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (10 Min.) #2`,
    description: `9 sedute da 10 minuti + 2 in omaggio`,
    price: 72,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (12 Min.) #1`,
    description: `5 sedute da 12 minuti + 1 in omaggio`,
    price: 45,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (12 Min.) #2`,
    description: `9 sedute da 12 minuti + 2 in omaggio`,
    price: 81,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (15 Min.) #1`,
    description: `5 sedute da 15 minuti + 1 in omaggio`,
    price: 60,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Abbonamento Solarium (15 Min.) #2`,
    description: `9 sedute da 15 minuti + 2 in omaggio`,
    price: 108,
    img: `style.png`,
    category: service_category.solarium,
  },
  {
    name: `Luce Pulsata Zona Piccola`,
    description: `Questo trattamento si applica singolarmente su: mento, baffetti, mani e piedi.\nDurante il trattamento un microprocessore controlla costantemente l'intensità di erogazione della luce per il massimo rispetto della pelle. Ksenon Premium rallenta e dirada progressivamente la crescita dei peli, rispettando l'integrità dei tessuti epidermici, senza arrossamenti, strappi dolorosi, follicoliti e peli incarniti. E' ottimale anche per la depilazione maschile, sempre più richiesta per esigenze legate alla moda, allo sport e alla bellezza.`,
    price: 30,
    img: `lp.webp`,
    category: service_category.luce_pulsata,
  },
  {
    name: `Luce Pulsata Zona Media`,
    description: `Questo trattamento si applica singolarmente su: inguine, ascelle, braccia (singola), mezzagamba (singola).\nDurante il trattamento un microprocessore controlla costantemente l'intensità di erogazione della luce per il massimo rispetto della pelle. Ksenon Premium rallenta e dirada progressivamente la crescita dei peli, rispettando l'integrità dei tessuti epidermici, senza arrossamenti, strappi dolorosi, follicoliti e peli incarniti. E' ottimale anche per la depilazione maschile, sempre più richiesta per esigenze legate alla moda, allo sport e alla bellezza.`,
    price: 45,
    img: `lp.webp`,
    category: service_category.luce_pulsata,
  },
  {
    name: `Luce Pulsata Zona Grande`,
    description: `Questo trattamento si applica singolarmente su: gamba intera (singola), petto e schiena.\nDurante il trattamento un microprocessore controlla costantemente l'intensità di erogazione della luce per il massimo rispetto della pelle. Ksenon Premium rallenta e dirada progressivamente la crescita dei peli, rispettando l'integrità dei tessuti epidermici, senza arrossamenti, strappi dolorosi, follicoliti e peli incarniti. E' ottimale anche per la depilazione maschile, sempre più richiesta per esigenze legate alla moda, allo sport e alla bellezza.`,
    price: 75,
    img: `lp.webp`,
    category: service_category.luce_pulsata,
  },
  {
    name: `Massaggio Rilassante Nella Grotta di Sale`,
    description: `Un magico momento di puro relax e benessere.<br/>\nPotrete godere di uno splendido massaggio nella Grotta di Sale.<br/>\nTutti i benefici del massaggio  uniti ai benefici della Grotta di Sale.Un connubio perfetto per raggiungere la tua armonia interiore e la tua bellezza esteriore`,
    price: 63,
    img: `mrngds.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Drenante Nella Grotta di Sale`,
    description: `Un magico momento di puro relax e benessere.<br>\nPotrete godere di uno splendido massaggio nella Grotta di Sale.<br>\nTutti i benefici del massaggio  uniti ai benefici della Grotta di Sale.Un connubio perfetto per raggiungere la tua armonia interiore e la tua bellezza esteriore.`,
    price: 75,
    img: `mdngds.webp`,
    category: service_category.corpo,
  },
  {
    name: `Massaggio Estetico Nella Grotta di Sale`,
    description: `Un magico momento di puro relax e benessere.<br>\nPotrete godere di uno splendido massaggio nella Grotta di Sale.<br>\nTutti i benefici del massaggio  uniti ai benefici della Grotta di Sale.Un connubio perfetto per raggiungere la tua armonia interiore e la tua bellezza esteriore.`,
    price: 50,
    img: `mengds.webp`,
    category: service_category.corpo,
  },
  {
    name: `Prenotazione Appuntamento`,
    description: `Per prenotare un appuntamento in sede prima devi chiamarci per stabilire la data e l'ora che desideri (vedi contattaci). Dopodiché dovrai effettuare l'acquisto di questo articolo come caparra confirmatoria.`,
    price: 20,
    img: `caparraConfirmatoria.webp`,
    category: service_category.appuntamento,
  },
  {
    name: `Abbonamento mani semipermanente 5+1`,
    description: `5 applicazioni+1 omaggio di manicure con smalto semipermanente`,
    price: 180,
    img: `ec.webp`,
    category: service_category.manicure,
  },
  {
    name: `Abbonamento di piedi semipermanente 5+1`,
    description: `5 applicazioni+1 omaggio di pedicure con smalto semipermanente`,
    price: 180,
    img: `ec.webp`,
    category: service_category.pedicure,
  },
];