/**
 * Script to update llms.txt with product and service data from DB
 *
 * Run: pnpm llms:update
 */
import fs from 'fs';
import path from 'path';
import { PrismaClient } from '@prisma/client';

const db = new PrismaClient();

const LLMS_TXT_PATH = path.join(process.cwd(), 'public/llms.txt');

// This marker separates manual content from auto-generated content
const AUTO_GENERATED_MARKER = '<!-- PRODUCTS FOR SALE ON THIS COSMETICS E-COMMERCE WEBSITE -->';

async function main() {
  console.log('Fetching products and services from database...');

  const [products, services] = await Promise.all([
    db.product.findMany({
      where: { active: true, deleted_at: null },
      include: { brand: true },
      orderBy: [{ category: 'asc' }, { name: 'asc' }],
    }),
    db.service.findMany({
      where: { active: true, deleted_at: null },
      orderBy: [{ category: 'asc' }, { name: 'asc' }],
    }),
  ]);

  console.log(`Found ${products.length} products and ${services.length} services`);

  // Read current llms.txt
  let content = fs.readFileSync(LLMS_TXT_PATH, 'utf-8');

  // Remove existing auto-generated section if present (everything after the marker)
  const markerIndex = content.indexOf(AUTO_GENERATED_MARKER);
  if (markerIndex !== -1) {
    content = content.substring(0, markerIndex).trimEnd();
  }

  // Group products by category
  const productsByCategory = products.reduce(
    (acc, product) => {
      const category = product.category || 'Altro';
      if (!acc[category]) acc[category] = [];
      acc[category].push(product);
      return acc;
    },
    {} as Record<string, typeof products>
  );

  // Group services by category
  const servicesByCategory = services.reduce(
    (acc, service) => {
      const category = service.category || 'Altro';
      if (!acc[category]) acc[category] = [];
      acc[category].push(service);
      return acc;
    },
    {} as Record<string, typeof services>
  );

  // Build auto-generated section
  let autoGenerated = `\n\n${AUTO_GENERATED_MARKER}\n`;

  // Products section
  autoGenerated += `\n## Catalogo Prodotti Disponibili\n\n`;
  autoGenerated += `I seguenti prodotti cosmetici professionali sono disponibili per l'acquisto sul sito svetlaestetica.com nella sezione /prodotti:\n\n`;

  for (const [category, categoryProducts] of Object.entries(productsByCategory)) {
    autoGenerated += `### ${category}\n\n`;
    for (const product of categoryProducts) {
      const brandName = product.brand?.name ? ` (${product.brand.name})` : '';
      autoGenerated += `- ${product.name}${brandName}\n`;
    }
    autoGenerated += '\n';
  }

  // Services section
  autoGenerated += `## Catalogo Trattamenti Disponibili\n\n`;
  autoGenerated += `I seguenti trattamenti estetici sono disponibili per la prenotazione sul sito svetlaestetica.com nella sezione /trattamenti:\n\n`;

  for (const [category, categoryServices] of Object.entries(servicesByCategory)) {
    autoGenerated += `### ${category}\n\n`;
    for (const service of categoryServices) {
      const duration = service.duration_min ? ` - ${service.duration_min} min` : '';
      autoGenerated += `- ${service.name}${duration}\n`;
    }
    autoGenerated += '\n';
  }

  // Combine content
  const updatedContent = content + autoGenerated;

  // Write back to file
  fs.writeFileSync(LLMS_TXT_PATH, updatedContent.trimEnd() + '\n');

  console.log('✅ llms.txt updated successfully!');
  console.log(
    `   - ${products.length} products in ${Object.keys(productsByCategory).length} categories`
  );
  console.log(
    `   - ${services.length} services in ${Object.keys(servicesByCategory).length} categories`
  );

  await db.$disconnect();
}

main().catch((e) => {
  console.error('Error updating llms.txt:', e);
  process.exit(1);
});
